/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectConway;

/**
 *
 * @author nathanhansen
 */
public class loseMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static int levelSel;
    public loseMenu(int level) {
        initComponents();
        levelSel = level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pausetitle = new java.awt.Label();
        RetryButton = new java.awt.Button();
        LevelSelectButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        pausetitle.setFont(new java.awt.Font("Copperplate", 0, 48)); // NOI18N
        pausetitle.setForeground(new java.awt.Color(0, 0, 0));
        pausetitle.setText("YOU LOSE!");
        getContentPane().add(pausetitle);
        pausetitle.setBounds(120, 0, 290, 200);

        RetryButton.setLabel("RETRY");
        RetryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetryButtonMouseClicked(evt);
            }
        });
        RetryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RetryButton);
        RetryButton.setBounds(140, 200, 210, 40);

        LevelSelectButton.setActionCommand("LevelSelect");
        LevelSelectButton.setLabel("LEVEL SELECT");
        LevelSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelSelectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LevelSelectButton);
        LevelSelectButton.setBounds(140, 250, 210, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RetryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetryButtonActionPerformed
        //open the game board and update the level variable to the same level that they were just on
        GameBoard sandbox = new GameBoard(levelSel);
        sandbox.setVisible(true);
        dispose(); // closes current frame
    }//GEN-LAST:event_RetryButtonActionPerformed

    private void LevelSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelSelectButtonActionPerformed
        //go to level select screen
        levelSelect lvlSel = new levelSelect();
        lvlSel.setVisible(true);
        dispose(); // closes current frame
    }//GEN-LAST:event_LevelSelectButtonActionPerformed

    private void RetryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetryButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RetryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loseMenu(levelSel).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button LevelSelectButton;
    private java.awt.Button RetryButton;
    private java.awt.Label pausetitle;
    // End of variables declaration//GEN-END:variables
}
