/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectConway;

/**
 *
 * @author nathanhansen
 */
public class pauseMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public pauseMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pausetitle = new java.awt.Label();
        resumebutton = new java.awt.Button();
        quitbutton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        pausetitle.setFont(new java.awt.Font("Copperplate", 0, 48)); // NOI18N
        pausetitle.setForeground(new java.awt.Color(0, 0, 0));
        pausetitle.setText("PAUSED");
        getContentPane().add(pausetitle);
        pausetitle.setBounds(149, 0, 200, 200);

        resumebutton.setLabel("RESUME");
        resumebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumebuttonMouseClicked(evt);
            }
        });
        resumebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resumebutton);
        resumebutton.setBounds(140, 200, 210, 40);

        quitbutton.setActionCommand("QUIT");
        quitbutton.setLabel("LEVEL SELECT");
        quitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(quitbutton);
        quitbutton.setBounds(140, 250, 210, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resumebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resumebuttonActionPerformed

    private void quitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitbuttonActionPerformed
        // TODO add your handling code here:
        //make it stop
    }//GEN-LAST:event_quitbuttonActionPerformed

    private void resumebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumebuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resumebuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pauseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new pauseMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label pausetitle;
    private java.awt.Button quitbutton;
    private java.awt.Button resumebutton;
    // End of variables declaration//GEN-END:variables
}
