/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectConway;

/**
 *
 * @author nathanhansen
 */
public class winMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public winMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pausetitle = new java.awt.Label();
        LevelSelectButton = new java.awt.Button();
        MenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menu");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        pausetitle.setFont(new java.awt.Font("Copperplate", 0, 48)); // NOI18N
        pausetitle.setForeground(new java.awt.Color(0, 0, 0));
        pausetitle.setText("YOU WIN!");
        getContentPane().add(pausetitle);
        pausetitle.setBounds(130, 0, 250, 200);

        LevelSelectButton.setActionCommand("QUIT");
        LevelSelectButton.setLabel("LEVEL SELECT");
        LevelSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelSelectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LevelSelectButton);
        LevelSelectButton.setBounds(140, 210, 210, 40);

        MenuButton.setText("MENU");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton);
        MenuButton.setBounds(140, 280, 210, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LevelSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelSelectButtonActionPerformed
        //go to level select screen
        levelSelect lvlSel = new levelSelect();
        lvlSel.setVisible(true);
        dispose(); // closes current frame
    }//GEN-LAST:event_LevelSelectButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // go back to main menu
        mainMenu mnMnu = new mainMenu();
        mnMnu.setVisible(true);
        dispose(); // closes current frame
    }//GEN-LAST:event_MenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new winMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button LevelSelectButton;
    private javax.swing.JButton MenuButton;
    private java.awt.Label pausetitle;
    // End of variables declaration//GEN-END:variables
}
